version: "3.8"
services:
  vpn:
    image: dperson/openvpn-client:latest
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    volumes:
      - ./openvpn:/vpn:ro
    ports:
      - 51413:51413/tcp
      - 51413:51413/udp
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
    logging:
      options:
        max-size: "2m"
        max-file: "3"
    environment:
      - FIREWALL
      - TZ=Europe/Paris
    networks:
      - proxy
      - torrenting
    labels:
      - "traefik.http.routers.joal.rule=Host(`joal.pi.valfur.fr`)"
      - "traefik.http.routers.joal.service=joal"
      - "traefik.http.services.joal.loadbalancer.server.port=4494"
      - "traefik.http.routers.transmission.rule=Host(`transmission.pi.valfur.fr`)"
      - "traefik.http.routers.transmission.service=transmission"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
      - "traefik.enable=true"
    restart: unless-stopped

  joal:
    build: joal
    container_name: joal
    restart: unless-stopped
    network_mode: "service:vpn"
    volumes:
      - ./joal/conf/torrents:/data/torrents
    command: ["--joal-conf=/data", "--spring.main.web-environment=true", "--server.port=4494", "--joal.ui.path.prefix=joal", "--joal.ui.secret-token=132465"]
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    network_mode: "service:vpn"
    volumes:
      - /transmission:/downloads
    restart: unless-stopped
  flaresolverr:
    image: flaresolverr/flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Paris
    networks:
      - indexer
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett
    depends_on:
      - flaresolverr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - jackett-config:/config
      - jackett-downloads:/downloads
    networks:
      - indexer
      - proxy
    labels:
      - "traefik.http.routers.jackett.rule=Host(`jackett.pi.valfur.fr`)"
      - "traefik.http.services.jackett.loadbalancer.server.port=9117"
      - "traefik.enable=true"
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - sonarr-config:/config
      - /transmission:/downloads
      - /media/series:/series
    networks:
      - indexer
      - proxy
      - torrenting
    labels:
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.pi.valfur.fr`)"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.enable=true"
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - radarr-config:/config
      - /transmission:/downloads
      - /media/movies:/movies
    networks:
      - indexer
      - proxy
      - torrenting
    labels:
      - "traefik.http.routers.radarr.rule=Host(`radarr.pi.valfur.fr`)"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.enable=true"
    restart: unless-stopped

volumes:
  jackett-config:
  jackett-downloads:
  sonarr-config:
  radarr-config:

networks:
  indexer:
  torrenting:
  proxy:
    external: true
