version: "3.8"
services:
  database:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - database:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
    networks:
      - backend
    restart: unless-stopped

  app:
    image: nextcloud:fpm
    volumes:
      - data:/var/www/html
      - /media/transmission/complete:/media:ro
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: database
      NEXTCLOUD_TRUSTED_DOMAINS: cloud.pi.valfur.fr
    networks:
      - backend
    restart: unless-stopped

  web:
    build: .
    volumes_from:
      - app
    networks:
      - backend
      - proxy
    labels:
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.pi.valfur.fr`)"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.enable=true"
    restart: unless-stopped

volumes:
  data:
  database:

networks:
  backend:
  proxy:
    external: true
