version: "3.8"
services:
  web:
    image: nginx
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - proxy
    labels:
      - "traefik.http.routers.web.rule=Host(`${DOMAIN}`)"
      - "traefik.enable=true"
    restart: unless-stopped

networks:
  proxy:
    external: true
